### ISSUE TITLE
Database Table Relations in Migrations

### ISSUE THREAD

**Issue by njaciklum** [musaddiq-ciklum/laravel-learning#16]
I can see the migrations, but no relations between the tables are defined in them. Kindly refer to https://laravel.com/docs/8.x/migrations#foreign-key-constraints for further detail.

**Comment by njaciklum** [comment]
Please keep me posted with the updates @musaddiq-ciklum

**Comment by musaddiq-ciklum** [comment]
@njaciklum thanks for reviewing and your valuable suggestion. I implemented the constraint using laravel conventions as highlighted in the attached snap. Please review this and let me know if it need to be changed. 

![laravel-db-constraints](https://user-images.githubusercontent.com/82140081/128172476-9edd3644-3c24-4fd7-8461-3b95c176233e.png)
