### ISSUE TITLE
Eloquent ORM Relationships is not used.

### ISSUE THREAD

**Issue by njaciklum** [musaddiq-ciklum/laravel-learning#17]
- Eloquent ORM is used which is a good thing, although Laravel prefer Eloquent ORM relation ships instead of db queries, kindly refer to https://laravel.com/docs/8.x/eloquent-relationships.
- Remove the db queries, use proper relationships in Model and fetch/insert data by using those relations.
- This will also help if you want to change the database drivers from mysql to any other e.g. postgresql by changing the configurations only.

**Comment by njaciklum** [comment]
Please keep me posted with the updates @musaddiq-ciklum

**Comment by musaddiq-ciklum** [comment]
@njaciklum Eloquent relationships are implemented. Please review and suggest if it need more improvement.
